INSERT INTO artists (artist_name, image_link) VALUES ('A Great Big World and Christina Aguilera', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Auli''i Cravalho', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Fun.', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Aladdin', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Idina Menzel', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Backstreet Boys', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Britney Spears', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('吴宗宪 & 温岚', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Spice Girls', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('*NSYNC', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Westlife', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Jay Chou', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Bruno Mars', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Taylor Swift', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Ed Sheeran', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Katy Perry', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('James Arthur', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Maroon 5', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Chris Brown', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Brian McKnight', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Sixpence None The Richer', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Shawn Mendes', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Adele', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('John Legend', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Christina Perri', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('The Calling', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Gotye', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Vanessa Carlton', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Lewis Capaldi', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('John Mayer', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Sam Smith', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Bigbang', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('2NE1', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Super Junior', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('宇多田ヒカル', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Misia', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('童子-T', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Say Something', 1, '-2U0Ivkn2Ds', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('How Far I''ll Go', 2, 'cPAbx5kgCJo', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('We are Young', 3, 'Sv6dMFF_yts','Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('A Whole New World', 4, 'aeDYx7Tkc7I', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Let It Go', 5, 'L0MK7qz13bU', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('I Want It That Way', 6, '4fndeDfaWCg', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Baby One More Time', 7, 'C-u5WLJ9Yk4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('屋顶', 8, 'hBQ7zeX_GRA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Wannabe', 9, 'gJLIiF15wjQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Bye Bye Bye', 10, 'Eo-KmOd3i7s', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('If I Let You Go', 11, '7NrQei36fJk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('不愛我就拉倒', 12, 'MAjY8mCTXWk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('24K Magic', 13, 'UqyT8IEBkvY', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Treasure', 13, 'nPvuNsRccVw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Cruel Summer', 14, 'GrKQvyXpNgc', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('We Are Never Ever Getting Back Together', 14, 'WA4iX5D9Z64', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Love Story', 14, '8xg3vE8Ie_E', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Shake It Off', 14, 'nfWlot6h_JM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Look What You Made Me Do', 14, '3tmd-ClpJxA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('The Lazy Song', 13, 'fLexgOxsZu0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Versace on the Floor', 13, '-FyjEnoIgTM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('That''s What I Like', 13, 'PMivT7MJ41M', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Grenade', 13, 'SR6iYWJxHqs', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('聽見下雨的聲音', 12, 'zqKoXPHhmsM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('給我一首歌的時間', 12, 'wt0RKW3aC84', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('算什麼男人', 12, 'HBqyVv13uL0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('告白氣球', 12, 'cGUx6verzZM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Thinking Out Loud', 15, 'lp-EO5I60KA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Photograph', 15, 'nSDgHBxUbVQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Shape of You', 15, 'JGwWNGJdvx8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Castle on the Hill', 15, 'K0ibBPhiaG0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Happier', 15, 'iWZmdoY1aTE', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Some Nights', 3, 'qQkBeOisNM0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Small Talk', 16, 'YqunQaPQumk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Never Really Over', 16, 'aEb5gNsmGJ8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Roar', 16, 'CevxZvSJLk8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Say You Won''t Let Go', 17, '0yW7w8F2TVA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Falling Like The Stars', 17, 'PMGY8fLwess', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Can I Be Him', 17, 'L3dPK8tDn6g', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Girls Like You ft. Cardi B', 18, 'aJOTlE1K90k', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Galway Girl', 15, '87gWaABqGYs', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Back To Love', 19, 'r7CWEE3ZAWs', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Sugar', 18, '09R8_2nJtjg', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Payphone ft. Wiz Khalifa', 18, 'KRaWnd3LJfs', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Misery', 18, '6g6g2mvItp4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Shape Of My Heart', 6, 'OT5msu-dap8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Chances', 6, 'W5kM5wAwRug', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Back At One', 20, 'rXPfovXw2tw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Somebody That I Used to Know', 27, '8UVNT4wvIGY', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Uptown Girl', 11, '0HTexqxo1og', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Wherever You Will Go', 26, 'iAP9AF6DCu4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('A Thousand Miles', 28, 'Cwkej79U3ek', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('A Thousand Years', 25, 'rtOvBOTyX00', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('All Of Me', 24, '450p7goxZqg', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Kiss Me', 21, 'v45F0YesdZM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('There She Goes', 21, '68MKLkNSMN4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('She Will Be Loved', 18, 'nIjVuRTm-dc', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Mercy', 22, 'KkGVmN68ByU', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Señorita', 22, 'Pkh8UtuejGw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('If I Can''t Have You', 22, 'oTJ-oqwxdZY', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Someone You Loved', 29, 'zABLecsR5UE', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('South of the Border ft. Cardi B', 15, '_KSKeR2juTI', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Set Fire To The Rain', 23, 'Ri7-vnrJD3k', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Hello', 23, 'YQHsXMglC9A', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Someone Like You', 23, 'hLQl3WQQoQ0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Waiting On the World to Change', 30, 'oBIxScJ5rlY', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('New Light', 30, 'mQ055hHdxbE', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Carry Me Away', 30, '6YDwBktDthA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Too Good At Goodbyes', 31, 'J_ub7Etch2U', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Stay With Me', 31, 'pB-5XG-DbAA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('뱅뱅뱅', 32, '2ips2mM7Zqw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('내가 제일 잘 나가', 33, 'j7_lSP8Vc3o', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('슈퍼주니어 ''쏘리 쏘리', 34, 'x6QA3m58DQw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');


INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('슈퍼주니어', 34, 'r6TwzSGYycM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('우리 사랑하지 말아요', 32, '9jTo6hTZmiQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('그리워해요', 33, 'AG0jlKdB1s0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('逢いたくていま', 36, 'MYo5alIaUOk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('忘れない日々', 36, '7-xChqpitwQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('花束を君に', 35, 'yCZFof7Y0tQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('光', 35, 'AlMdDpUWFFI', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('もう一度', 37, 'GUz8_NrMSCM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO sessions (session_name) VALUES ('emo monday');
INSERT INTO sessions (session_name) VALUES ('retro');
INSERT INTO sessions (session_name) VALUES ('boyband');
INSERT INTO sessions (session_name) VALUES ('chinese hits');
INSERT INTO sessions (session_name) VALUES ('ost');

INSERT INTO sessions_songs (session_id, song_id) VALUES (1,1);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,5);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,5);